### ISSUE TITLE
Automated rate limiting

### ISSUE THREAD

**Issue by hhoppe** [wimglenn/advent-of-code-data#137] opened 2023-12-26 17:56 UTC
The code explains:

```
# made 4 requests within 3 seconds - you're past the speed limit
# of 1 req/second and will get a delay of 160ms initially, then
# increasing exponentially on subsequent occasions
```

It would be useful if the code would instead issue a warning and automatically apply the right amount of delay (not exponentially increasing) to satisfy the speed limit.

My scenario: after completing aoc, I switch to a second login account and want to rerun my entire notebook of solutions on the new puzzle inputs to validate that the algorithms generalize correctly.

**Comment by wimglenn** [comment] 2023-12-27 00:18
The delay will be capped in the next release. 

The code is already logging warnings when the rate limiter is hit, it just means that caches are cold and is informational in this use-case (running already worked-out solution code through a fresh token).

Dupe of https://github.com/wimglenn/advent-of-code-data/issues/132

**Closed by wimglenn** 2023-12-27 00:18 UTC
